services:
  backend:
    image: lenvigo/backend:v1
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    image: lenvigo/frontend:v1
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80" 
    
